/**
 * my api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
    HttpClient, HttpHeaders, HttpParams,
    HttpResponse, HttpEvent
} from '@angular/common/http';

import { Observable } from 'rxjs/Observable';

import { AddRemoveProductResult } from '../model/addRemoveProductResult';
import { Cart } from '../model/cart';
import { IncDecRequest } from '../model/incDecRequest';


@Injectable()
export class CartService {


    constructor(protected httpClient: HttpClient) {
    }

    public Current(): Observable<Cart> {
        return this.httpClient.get<Cart>('/api/Cart/current',
            {
                observe: 'body',
                reportProgress: false
            }
        );
    }

    public Update(cart: Cart): Observable<Cart> {
        return this.httpClient.post<Cart>('/api/Cart',
            cart,
            {
                observe: 'body',
                reportProgress: false
            }
        );
    }

    // public ChangeCount(productId?: string, quantity?: number): Observable<QuantityResult>
    // {
    //     return this.httpClient.post<QuantityResult>('/api/Cart/quantity',
    //         { 
    //             productId: productId,
    //             quantity : quantity},
    //         {
    //             observe: 'body',
    //             reportProgress: false
    //         }
    //     );
    // }

    public Inc(productId: string, variationId: string): Observable<AddRemoveProductResult> {
        let param = new IncDecRequest();
        param.productId = productId;
        param.variationId = variationId;
        return this.httpClient.post<AddRemoveProductResult>('/api/Cart/add',
            param,
            {
                observe: 'body',
                reportProgress: false
            }
        );
    }

    // public Dec(productId?: string): Observable<AddRemoveProductResult>
    // {
    //     return this.httpClient.post<AddRemoveProductResult>('/api/Cart/remove',
    //         { productId: productId},
    //         {
    //             observe: 'body',
    //             reportProgress: false
    //         }
    //     );
    // }

    public getAll(): Observable<Cart[]> {
        return this.httpClient.get<Cart[]>('/api/cart',
            {
                observe: 'body',
                reportProgress: false,
            }
        );
    }

}
