/**
 * my api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
    HttpClient, HttpHeaders, HttpParams,
    HttpResponse, HttpEvent
} from '@angular/common/http';

import { Observable } from 'rxjs/Observable';

import { User } from '../model/user';

@Injectable()
export class UserService {

    constructor(protected httpClient: HttpClient) {
    }

    public getAll(): Observable<User[]> {
        return this.httpClient.get<User[]>('/api/user',
            {
                observe: 'body',
                reportProgress: false,
            }
        );
    }

}
