/**
 * my api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GroupChildDesc } from './groupChildDesc';


export class GroupDesc {
    title?: string;
    id?: string;
    visible?: boolean;
    child?: Array<GroupChildDesc>;
}
